services:
  mysql:
    extends:
      file: compose-mysql.yaml
      service: mysql
    volumes:
      - sql-data:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d
  api:
    build: .
    command: yarn start:dev
    environment:
      - PORT=${PORT}
      - MYSQL_HOST=mysql
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  sql-data:
