name: NestJS

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.js'
      - 'package.json'
      - 'yarn.lock'
      - 'Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.js'
      - 'package.json'
      - 'yarn.lock'
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Check format
        run: yarn format:check
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Tests
        run: yarn test
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile \
            --tag ${{ github.repository }}:${{ github.sha }} \
            --cache-from type=gha \
            --cache-to type=gha,mode=max
